const SET_TEXT = 'SET_TEXT';
const SET_EXTRAS = 'SET_EXTRAS';
const SET_EXTRAS_FROM_PAGE_TWO = 'SET_EXTRAS_FROM_PAGE_TWO';
const CLEAR_EXTRAS_FROM_PAGE_TWO = 'CLEAR_EXTRAS_FROM_PAGE_TWO';

export {
  SET_TEXT,
  SET_EXTRAS,
  SET_EXTRAS_FROM_PAGE_TWO,
  CLEAR_EXTRAS_FROM_PAGE_TWO
};
