const ACCOUNTS_DATA_LOADING = "ACCOUNTS_DATA_LOADING",
  SET_ACCOUNTS_DATA = "SET_ACCOUNTS_DATA",
  REMOVETESTATE = "REMOVETESTATE";

export { ACCOUNTS_DATA_LOADING, SET_ACCOUNTS_DATA, REMOVETESTATE };
