
const SET_DETAILS_DATA = "SET_DETAILS_DATA";
const DETAILS_DATA_LOADING="DETAILS_DATA_LOADING"
const SET_DETAILS_DATA_CREDIT="SET_DETAILS_DATA_CREDIT"
export {
  SET_DETAILS_DATA,
  DETAILS_DATA_LOADING,
  SET_DETAILS_DATA_CREDIT
};
